version: '3.8'

services:
  oauth2-api-tester:
    build: .
    container_name: oauth2-api-tester
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount SSL certificates if using HTTPS
      - ./cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./key.pem:/etc/ssl/certs/key.pem:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jwt-client-network

  # Optional: Add a development service for hot reloading
  oauth2-api-tester-dev:
    image: node:20-alpine
    container_name: oauth2-api-tester-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npm start -- --host 0.0.0.0 --port 4200
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    networks:
      - jwt-client-network

  # Optional: OAuth callback server for development
  oauth-callback-server:
    image: node:20-alpine
    container_name: oauth-callback-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: node scripts/oauth-callback-server.js
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    networks:
      - jwt-client-network

networks:
  jwt-client-network:
    driver: bridge
